package disch

const (
	a = ":regional_indicator_a:"
	b = ":regional_indicator_b:"
	c = ":regional_indicator_c:"
	d = ":regional_indicator_d:"
	e = ":regional_indicator_e:"
	f = ":regional_indicator_f:"
	g = ":regional_indicator_g:"
	h = ":regional_indicator_h:"
	i = ":regional_indicator_i:"
	j = ":regional_indicator_j:"
	k = ":regional_indicator_k:"
	l = ":regional_indicator_l:"
	m = ":regional_indicator_m:"
	n = ":regional_indicator_n:"
	o = ":regional_indicator_o:"
	p = ":regional_indicator_p:"
	q = ":regional_indicator_q:"
	r = ":regional_indicator_r:"
	s = ":regional_indicator_s:"
	t = ":regional_indicator_t:"
	u = ":regional_indicator_u:"
	v = ":regional_indicator_v:"
	w = ":regional_indicator_w:"
	x = ":regional_indicator_x:"
	y = ":regional_indicator_y:"
	z = ":regional_indicator_z:"
)

const (
	ka  = ":regional_indicator_k: :regional_indicator_a:"
	ki  = ":regional_indicator_k: :regional_indicator_i:"
	ku  = ":regional_indicator_k: :regional_indicator_u:"
	ke  = ":regional_indicator_k: :regional_indicator_e:"
	ko  = ":regional_indicator_k: :regional_indicator_o:"
	sa  = ":regional_indicator_s: :regional_indicator_a:"
	shi = ":regional_indicator_s: :regional_indicator_h: :regional_indicator_i:"
	su  = ":regional_indicator_s: :regional_indicator_u:"
	se  = ":regional_indicator_s: :regional_indicator_e:"
	so  = ":regional_indicator_s: :regional_indicator_o:"
	ta  = ":regional_indicator_t: :regional_indicator_a:"
	chi = ":regional_indicator_c: :regional_indicator_h: :regional_indicator_i:"
	tsu = ":regional_indicator_t: :regional_indicator_s: :regional_indicator_u:"
	te  = ":regional_indicator_t: :regional_indicator_e:"
	to  = ":regional_indicator_t: :regional_indicator_o:"
	na  = ":regional_indicator_n: :regional_indicator_a:"
	ni  = ":regional_indicator_n: :regional_indicator_i:"
	nu  = ":regional_indicator_n: :regional_indicator_u:"
	ne  = ":regional_indicator_n: :regional_indicator_e:"
	no  = ":regional_indicator_n: :regional_indicator_o:"
	ha  = ":regional_indicator_h: :regional_indicator_a:"
	hi  = ":regional_indicator_h: :regional_indicator_i:"
	hu  = ":regional_indicator_h: :regional_indicator_u:"
	he  = ":regional_indicator_h: :regional_indicator_e:"
	ho  = ":regional_indicator_h: :regional_indicator_o:"
	ma  = ":regional_indicator_m: :regional_indicator_a:"
	mi  = ":regional_indicator_m: :regional_indicator_i:"
	mu  = ":regional_indicator_m: :regional_indicator_u:"
	me  = ":regional_indicator_m: :regional_indicator_e:"
	mo  = ":regional_indicator_m: :regional_indicator_o:"
	ya  = ":regional_indicator_y: :regional_indicator_a:"
	yu  = ":regional_indicator_y: :regional_indicator_u:"
	yo  = ":regional_indicator_y: :regional_indicator_o:"
	ra  = ":regional_indicator_r: :regional_indicator_a:"
	ri  = ":regional_indicator_r: :regional_indicator_i:"
	ru  = ":regional_indicator_r: :regional_indicator_u:"
	re  = ":regional_indicator_r: :regional_indicator_e:"
	ro  = ":regional_indicator_r: :regional_indicator_o:"
	wa  = ":regional_indicator_w: :regional_indicator_a:"
	wo  = ":regional_indicator_w: :regional_indicator_o:"
	ga  = ":regional_indicator_g: :regional_indicator_a:"
	gi  = ":regional_indicator_g: :regional_indicator_i:"
	gu  = ":regional_indicator_g: :regional_indicator_u:"
	ge  = ":regional_indicator_g: :regional_indicator_e:"
	goo = ":regional_indicator_g: :regional_indicator_o:"
	za  = ":regional_indicator_z: :regional_indicator_a:"
	zi  = ":regional_indicator_j: :regional_indicator_i:"
	zu  = ":regional_indicator_z: :regional_indicator_u:"
	ze  = ":regional_indicator_z: :regional_indicator_e:"
	zo  = ":regional_indicator_z: :regional_indicator_o:"
	da  = ":regional_indicator_d: :regional_indicator_a:"
	di  = ":regional_indicator_d: :regional_indicator_i:"
	du  = ":regional_indicator_d: :regional_indicator_u:"
	de  = ":regional_indicator_d: :regional_indicator_e:"
	do  = ":regional_indicator_d: :regional_indicator_o:"
	ba  = ":regional_indicator_b: :regional_indicator_a:"
	bi  = ":regional_indicator_b: :regional_indicator_i:"
	bu  = ":regional_indicator_b: :regional_indicator_u:"
	be  = ":regional_indicator_b: :regional_indicator_e:"
	bo  = ":regional_indicator_b: :regional_indicator_o:"
	pa  = ":regional_indicator_p: :regional_indicator_a:"
	pi  = ":regional_indicator_p: :regional_indicator_i:"
	pu  = ":regional_indicator_p: :regional_indicator_u:"
	pe  = ":regional_indicator_p: :regional_indicator_e:"
	po  = ":regional_indicator_p: :regional_indicator_o:"
)

const (
	zero  = ":zero:"
	one   = ":one:"
	two   = ":two:"
	three = ":three:"
	four  = ":four:"
	five  = ":five:"
	six   = ":six:"
	seven = ":seven:"
	eight = ":eight:"
	nine  = ":nine:"
)

const (
	exclamation = ":bangbang:"
	question    = ":question:"
	hyphen      = ":heavy_minus_sign:"
)
